### ISSUE TITLE
Running "pypeek --help" starts downloading precompiled ffmpeg binaries?!

### ISSUE THREAD

**Issue by hartwork** [firatkiral/pypeek#1]
Hi @firatkiral ,

when I run `pypeek --help` it starts to download pre-compiled ffmpeg binaries:

```console
# pypeek --help
Installing ffmpeg to /tmp/tmp.PqUazPhkz1/pypeek/venv/lib/python3.11/site-packages/pypeek/bin/linux
Downloading https://github.com/zackees/ffmpeg_bins/raw/main/v5.0/linux.zip -> /tmp/tmp.PqUazPhkz1/pypeek/venv/lib/python3.11/site-packages/pypeek/bin/linux.zip
..........................................^CTraceback (most recent call last):
  [..]
  File "/tmp/tmp.PqUazPhkz1/pypeek/venv/lib/python3.11/site-packages/pypeek/main.py", line 15, in <module>
    get_ffmpeg()
  File "/tmp/tmp.PqUazPhkz1/pypeek/venv/lib/python3.11/site-packages/pypeek/ffmpeg.py", line 92, in get_ffmpeg
    ffmpeg, _ = get_or_fetch_platform_executables_else_raise()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.PqUazPhkz1/pypeek/venv/lib/python3.11/site-packages/pypeek/ffmpeg.py", line 61, in get_or_fetch_platform_executables_else_raise
    download_file(url, local_zip)
  [..]
KeyboardInterrupt
```

That is unexpected, unfortunate and scary in my world:
- `--help` should never do things like that, display some help quick, and get out of the way.
- I'm on a source-based Linux distro and don't trust most people's binaries, so downloading binaries by a third party unknown to me is not nice.
- With a package manager around, why would I want ffmpeg binaries that are not provided by my distro? That's what I have a package manager for.
- PS: ffmpeg 5.0(.0) and these binaries are ~12 months old

Please re-consider these choices, these are by no means sane defaults. Thank you!

Best, Sebastian

**Comment by firatkiral** [comment]
@hartwork, windows and mac users are considered here to avoid external steps to install peek. I'll try to make this optional. Thanks.

**Comment by hartwork** [comment]
@firatkiral thank you!

For macOS, `brew install ffmpeg` could be an option. For Windows, ffmpeg upstream lists alternative Windows builds at https://ffmpeg.org/download.html — maybe these would be options closer to trustable and up-to-date, not sure.

**Comment by firatkiral** [comment]
--help issue fixed. Downloading ffmpeg is optional now, only asks to download if ffmpeg is not in the system path.

**Comment by hartwork** [comment]
@firatkiral that's a big improvement, thanks a lot! :+1:
