### ISSUE TITLE
pypeek --shortcut generates invalid shortcut on Windows

### ISSUE THREAD

**Issue by metal450** [firatkiral/pypeek#19]
When running `pypeek --shortcut`, the resulting shortcut's target is `C:\Users\<username>\Desktop\peek-gui`, which does not work. It must be manually updated to `C:\Users\<username>\AppData\Local\Programs\Python\Python310\Scripts\pypeek-gui.exe`.

**Comment by firatkiral** [comment]
fixed, please upgrade to 2.9.10

`pip install --upgrade pypeek`
