### ISSUE TITLE
Area selection does not work in i3

### ISSUE THREAD

**Issue by AlexDaniel** [firatkiral/pypeek#26]
When running in i3, the area selection does not seem to work at all. pypeek simply records the full screen at all times.

![Peek 2024-02-13 15-27](https://github.com/firatkiral/pypeek/assets/5507503/46a456b7-a12e-41d8-9738-bb6992209e8c)

It seems that unlike peek, pypeek starts as a normal window. In i3 that means that the area of the screen is split and some place and size is given to pypeek. Instead, it should be a floating window that is resizable by itself. Now, I made it floating myself by using a shortcut, but that forced the pypeek window to be of a minimum size. So, in general, in i3 it seems that pypeek can only record the full screen (which honestly defeats the purpose).

**Comment by firatkiral** [comment]
Hi, yes it starts full screen mode, can you please switch the window mode by clicking screen icon in the middle.

**Comment by AlexDaniel** [comment]
Oooh, yes, that's it! Thank you!
Feel free to close, unless you want to somehow detect that automatically somehow.
