### ISSUE TITLE
Where are recordings saved to in Mac?

### ISSUE THREAD

**Issue by DaniGuardiola** [firatkiral/pypeek#28]
I can't find where recordings are saved, I've looked everywhere. Installed from the app store. Thank you.

**Comment by vedanta-tabist** [comment]
I also found this issue, I already record the screen, but when click save, it only show "calculating..." and then do nothing

**Comment by firatkiral** [comment]
Its supposed to open file save dialog once recording or screenshot is done. It only supports arm machines with "M" chips

You may try to remove and reinstall and make sure it has recording permission.
![peek_1](https://github.com/firatkiral/pypeek/assets/27867155/9ecbfa51-3151-437c-bd56-b2146e748887)

Please let me know what your system is.

**Comment by firatkiral** [comment]
Hey @DaniGuardiola, @vedanta-tabist, 

If it saves screeenshots but not videos, then it's probably the compatibility issue of fmpeg. Would you be able to install rosetta and try again. 

Open terminal and run this:
`softwareupdate --install-rosetta`

[Rosetta](https://en.wikipedia.org/wiki/Rosetta_(software)) is an Apples's official compatibility layer between x64 binaries and arm.

**Comment by vedanta-tabist** [comment]
solved! thanks!
