### ISSUE TITLE
Use of name "pypeek" versus "peek"

### ISSUE THREAD

**Issue by hartwork** [firatkiral/pypeek#3]
Hi!

Just a quick note that the app uses both "pypeek" and "peek" for a name at different places. I would like to suggest to use "pypeek" only and consistently. Just an idea.

Best, Sebastian

**Comment by hartwork** [comment]
This should not be a bug, it's your call, nevermind, closing.

**Comment by firatkiral** [comment]
@hartwork, idea is keeping app's name Peek as original. Only python package and class name is pypeek as it's availabe on pypi.
