### ISSUE TITLE
Duplicate pypeek repository

### ISSUE THREAD

**Issue by mcmxcdev** [firatkiral/pypeek#5]
Noticed from a quick search that there is both https://github.com/firatkiral/pypeek and https://github.com/pypeek/pypeek

It would make sense to remove the one that is not actively maintained so it is clearer to potential users.

Personally, I think that https://github.com/pypeek/pypeek would look more official but not a big deal.

**Comment by firatkiral** [comment]
I agree, fixed. Thanks.
