### ISSUE TITLE
Some thoughts regarding packaging and about this application

### ISSUE THREAD

**Issue by D3SOX** [firatkiral/pypeek#9]
I have created an initial package for Arch Linux [on the AUR](https://aur.archlinux.org/packages/pypeek-git)

Some things that came to my mind:
- I saw that you're already [versioning the app on PyPI](https://pypi.org/project/pypeek/#history). It would be nice if you could also create git tags for each release. I can make a versioned package too – downloading the source from PyPI, but I'd prefer it to be fetched directly from the source repository.
- I'm currently [generating a desktop entry](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pypeek-git#n34) for the app inside the package. It would be nice if you could include a `.desktop` file for Linux somewhere.
  - Here is what's generated by that command for reference

<details>
  <summary>
      <code>pypeek.desktop</code>
  </summary>

```ini
[Desktop Entry]
Version=1.0
Type=Application
Name=Pypeek
Comment=Simple animated GIF screen recorder with an easy to use interface
Exec=pypeek
Icon=pypeek
Terminal=false
StartupNotify=false
Categories=Utility;
````
</details>

- ~~I saw inside `src/pypeek/ffmpeg.py` that you're downloading FFMPEG binaries from ZIP files inside this repo. I think you should prefer using the system's `ffmpeg` if it's in the `$PATH` and only download if it's not available/compatible.~~ → Never mind, it seems to use system ffmpeg already
- The config and log file is created inside the user's home directory. I think this should reside
  - For Linux in `$XDG_CONFIG_HOME/pypeek` if set, otherwise `$HOME/.config/pypeek`
  - For Windows in `%appdata%\pypeek`
  - For macOS in `~/Library/Preferences/com.github.pypeek` (not entirely sure about that)
- I think it would be nice if the default file name when saving could include a timestamp so that when you create multiple GIFs in a row you don't have to change it manually
- Why is this repo a fork of the other Peek? It doesn't share any code. I think it should be its own repo, especially because currently every time you clone this repo you also automatically get the history from Peek.
- The UI doesn't honor system preferences for window decorations. For example, I have my window buttons all on the left (like on macOS) but pypeek shows the close button on the right

**Comment by D3SOX** [comment]
Any thoughts on this?

**Comment by firatkiral** [comment]
@D3SOX, I agree most of them and addressed. 
UI uses frameless window (no header) to have more space on top and has its own header same across all os platforms. I'll try to add stable version releases to github as well. 

- Now it supports linux shortcut, it will add a desktop entry to applications. 
- I added incremental file saving. 
- Config files are saving to corresponding folders of each os platform.

Thank you.

**Comment by firatkiral** [comment]
closing.
